---
title: "Hw-07-ChenchenGuo"
author: "Chenchen GUO"
date: "Nov 8th, 2018"
output: github_document
always_allow_html: yes
---

-   [Introduction](#introduction)

    -[Goals](#goals)
-   [Part1: Create Package](#part-1-create-package)

    -[Requirements](#requirements)
    
    -[Implementation](#implementation)

    
    

Introduction
------------

[Homework 07](http://stat545.com/Classroom/assignments/hw07/hw07.html): Factor and figure management
The aim of the homework is to create own R package and add function to the powers R package.

Goals:
-----------

1. Define and export one new function, i.e. make it available to a user upon loading the package.
2. Give function arguments sensible defaults, where relevant.
3. Document all exported functions.
4. Include at least three unit tests for your new function that test common use cases that you anticipate of the function.
5. Your package should pass check() without errors (warnings and notes are OK).
6. Update the README and vignette to show usage of all the functions in the package.
7. Modify the instructions telling someone how to install your package.

Part 1: Create Package
-------------------------

Requirements
------------
1. From the above

Implementation
--------------